Feat/env
san-ghun/minishell pull request #53
Opened 2023-08-14 22:17 UTC by miooo0o

### brief
The primary function of `ft_env` is not complete.
I've created a primary process that converts env to a Doubly Linked List (DLL), a subfunction that converts the DLL back to a `char ** array`, and a struct to execute it.

The subfunctions for the DLL are in src/t_env and are all tested. There willn't be any memory issues.

**add new**
-  minishell.h  : (struct) t_env, t_elst
- src/built-in/ft_env.c
- src/t_env : env_add, env_del, env_init

**norm**
src/t_env, utill, built-in.
- except  "comment is invalid in this scope" / ft_env

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```shell
$ toto="somevalue"
$ MY_VAR="$toto"
$ echo $MY_VAR
somevalue
$ 
```
These functions were created assuming the above situation!

### minishell.h, new struct
> t_env & t_elst

```c
// struct t_env
/// @brief This struct was created with a doubly linked list
/// but can work like a deque.
/// There is a difference which is that it can be inserted and deleted
/// even if it is on an intermediate node.
/// @note Designed for env, but can be used anywhere else you need
/// to insert or delete.
/// @param key where the head of envp (i.e., before '=') is stored as 'key' 
/// @param value the value of envp (i.e., after '=') is stored.
/// Both 'key' and 'value' are dynamically allocated!
typedef struct s_env
{
	char			*key;
	char			*value;
	struct s_env	*prev;
	struct s_env	*next;
}			t_env;

/// @note For convenience, unify the internal parameter names as other.
/// @param begin front node
/// @param end rear node
typedef struct s_elst
{
	t_env	*begin;
	t_env	*end;
	int		size;
}			t_elst;
```

Assume that `envp[i]` is organized like this **`KEY=VALUE\0`**

The two structures above store environment variables are divided into key and value. This list is created considering that our shell may later set the environment variables anew or modify their values.

I don't think this is strictly necessary, as I've ( and you also) already used DLLs, and some of them can be adapted from libraries I've created in the past, so I've gone back to using DLLs, albeit with a bit of complexity

### src/built-in/ft_env.c

As already mentioned, the functions currently created are basic to complete ft_env. Nevertheless, I'm pulling these functions to show how I will manipulate `env` and how to implement `$` and `$?` following later work.

I believe to use the current form to make modifying `$` and `$?` a little more comfortable.

```
t_elst *env_to_dll(char **envp)
```
This function treats `envp[i]` as **`KEY=VALUE\0`** and stores the key and value in the node with memory allocations for each. I created this function with the premise that each string can be modified via different commands (like `$`).

@note: The function contains a bit of a long line, I'll comment it out so you can see it in review.

```
char **dll_to_envp(t_elst *lst)
```
This function takes a command line split into key and value and puts them back together as **`KEY=VALUE\0`**.
This function contains a slightly unclean line, which we'll comment on so that you can see it in the review.

### src/t_env : env_add, env_del, env_init
These are the basic DLL functions, except for the ones below.

```
void env_add_or_update(t_elst *data, char *key, char *value)
```

This function is intended for situations where you need to modify part of an envp using `$` or add a new envp.

2023-08-14 23:05 UTC, miooo0o reviewed
리뷰 추가했습니다!
더 설명이 필요하다면 다음 미팅에서 이야기해보아요

2023-08-14 23:05 UTC, miooo0o commented on src/t_env/env_add.c
> +		if (ft_strcmp(current->key, key) == 0)
앗챠 여기서 쓰려고 했구나! 나중에 수정하곘습니다. 지금 보니까 FOUND도 전달력이 좋지는 않네요.
의견 있으시면 알려주셔요.

```c
if (ft_strcmp(current->key, key) == STATUS_FOUND)
```

2023-08-14 23:05 UTC, miooo0o commented on src/t_env/env_add.c
> +void	env_add_or_update(t_elst *data, char *key, char *value)
환경 변수에 추가되거나 업데이트 되야하는 상황을 상정하고 만들었습니다.

```
$ alias ll="ls -la"
$ export PATH=$PATH:/new/directory/path
$ export NEW_VARIABLE=value
```

2023-08-14 23:05 UTC, miooo0o commented on src/util/ft_strequ.c
> +int	ft_strequ(char const *s1, char const *s2)
norm : 완료!

2023-08-14 23:05 UTC, miooo0o commented on src/util/ft_strcdup.c
> +	int		i;
norm : 완료!

2023-08-14 23:05 UTC, miooo0o commented on test.c
> +void ft_print_env(t_env *node)
테스트 함수입니다. 지우셔도 무방합니다

2023-08-17 09:14 UTC, san-ghun requested changes
`built-in/ft_env.c`
`char **dll_to_envp()`에 `key_len` `value_len` 두개 변수를 사용하지 않는다고 컴파일 체크에서 징징거리네요 ㅠ 이것 두개만 제거해서 푸시 부탁드려요.

2023-08-17 09:14 UTC, san-ghun commented on src/built-in/ft_env.c
> +			node = env_newnode(ft_substr(envp[i], 0, separator - envp[i]), \
오.... 엄청납니다 ㅎㄷㄷ

2023-08-17 09:14 UTC, san-ghun commented on src/t_env/env_add.c
> +void	env_add_or_update(t_elst *data, char *key, char *value)
감사합니다 참고할게요!

2023-08-17 09:14 UTC, san-ghun commented on src/t_env/env_del.c
> +	env_updatesize(list, -1);
노드를 리셋하고 프리해주는거 뭔가 우아하네요 ㅎㅎ 하나 또 배웁니다 감사 ㅎㅎ

2023-08-17 09:14 UTC, san-ghun commented on src/built-in/ft_env.c
> +	size_t	value_len;
`key_len` `value_len` 두개 변수를 사용하지 않는다고 컴파일 체크에서 징징거리네요 ㅠ 이것 두개만 제거해서 푸시 부탁드려요

2023-08-17 09:16 UTC, san-ghun commented
Leaving referenced issues for the PR.
#28 #30 #31 #29

2023-08-17 18:17 UTC, miooo0o commented
Cleared unused parameters.

2023-08-17 19:41 UTC, san-ghun approved these changes

2023-08-17 19:42 UTC, merged